---
- name: add repository ppa:openjdk-r/ppa
  apt_repository: repo=ppa:openjdk-r/ppa update_cache=yes state=present

- name: install required packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - maven
    - openbox
    - openjdk-8-jdk
    - tint2
    - x11-xkb-utils

- name: update java alternatives
  command: update-java-alternatives -s {{ java_version }}

- name: install tigervnc
  apt: deb={{ tigervnc_url }}

- name: configure vnc service
  lineinfile: dest=/etc/default/vncservers create=yes line="VNCSERVERS=0:{{ user }}"

# random password generation, currently disabled due to external limitations
# - name: add new user {{ user }}
#   user: name={{ user }} password={{ lookup("password", "/tmp/ansible-{{ user }}-password encrypt=sha256_crypt") }} shell=/bin/bash groups=adm,sudo system=yes

- name: add new user {{ user }}
  user: name={{ user }} password={{ password_crypt }} shell=/bin/bash groups=adm,sudo

- name: create required directories
  file: path={{ item }} state=directory owner={{ user }} group={{ user }} mode="u=rwx"
  with_items:
    - /home/{{ user }}/.config/openbox
    - /home/{{ user }}/.vnc
    - /home/{{ user }}/ophidia

- name: copy configuration files
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ user }} group={{ user }} mode={{ item.mode }}
  with_items:
      - { src: "dotconfig_openbox_autostart", dest: "/home/{{ user }}/.config/openbox/autostart", mode: "u=rw" }
      - { src: "dotconfig_openbox_menu.xml", dest: "/home/{{ user }}/.config/openbox/menu.xml", mode: "u=rw" }
      - { src: "dotvnc_xstartup", dest: "/home/{{ user }}/.vnc/xstartup", mode: "u=rwx" }
      - { src: "ophidia_oph-credentials.txt", dest: "/home/{{ user }}/ophidia/oph-credentials.txt", mode: "u=rw" }

- name: prepare kepler launcher in menu which uses correct environment variables
  template: src=kepler.j2 dest=/usr/bin/kepler mode="u=rwx,g=rx,o=rx"

# random password generation, currently disabled due to external limitations
# - name: create password file for vnc
#   shell: echo {{ lookup("password", "/tmp/ansible-vnc-password") }} | vncpasswd -f > /home/{{ user }}/.vnc/passwd

- name: create password file for vnc
  shell: echo {{ password_vnc }} | vncpasswd -f > /home/{{ user }}/.vnc/passwd

- name: set valid mode for password file for vnc
  file: owner={{ user }} group={{ user }} mode="u=rw,g=,o=" path=/home/{{ user }}/.vnc/passwd

- name: install kepler 2.5
  unarchive: src={{ kepler_url }} dest=/usr/local copy=no keep_newer=yes

- name: git-clone indigoclient and indigokepler
  git: repo={{ item.repo }} dest={{ item.dest }} version={{ item.ver }} clone=yes
  with_items:
    - { repo: "https://github.com/indigo-dc/indigoclient.git", dest: "/usr/local/indigoclient", ver: "{{ indigo_kepler_version }}" }
    - { repo: "https://github.com/indigo-dc/indigokepler.git", dest: "/usr/local/indigokepler", ver: "{{ indigo_kepler_version }}" }

- name: compile indigoclient
  command: mvn install chdir=/usr/local/indigoclient

- name: prepare indigokepler
  command: mvn initialize chdir=/usr/local/indigokepler

- name: compile indigokepler
  command: mvn install dependency:copy-dependencies -DoutputDirectory=target/indigo/lib/jar -DexcludeArtifactIds=ptolemy chdir=/usr/local/indigokepler

- name: install indigo module in kepler directory
  command: /bin/cp -r /usr/local/indigokepler/target/indigo {{ kepler_home }}/

- name: configure kepler to use indigo module
  lineinfile: dest={{ kepler_home }}/build-area/modules.txt insertbefore=BOF line=indigo

- name: copy indigo workflows
  command: cp -r {{ item.src }} {{ item.dest }}
  with_items:
    - { src: "/usr/local/indigokepler/workflows/ophidia/", dest: "/home/{{ user }}/ophidia/" }
    - { src: "/usr/local/indigokepler/workflows/ophidia/pilot/OphidiaPilot.kar", dest: "/home/{{ user }}/OphidiaClimateDocker.kar" }

- name: start and enable vnc service
  service: name=vncserver state=started enabled=yes
