---
- name: add repository ppa:openjdk-r/ppa
  apt_repository: repo='ppa:openjdk-r/ppa' update_cache=yes state=present

- name: Install packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - software-properties-common
    - build-essential
    - ant
    - git
    - maven
    - openjdk-8-jdk
    - r-base
    - ssh-import-id
    - tar
    - time
    - ttf-ubuntu-font-family
    - curl
    - x11-utils
    - x11-xkb-utils
    - xauth
    - libfontenc1
    - libgl1-mesa-dri
    - libgnutls28
    - libtasn1-3-bin
    - libxfont1
    - libglu1-mesa
    - openbox
    - tint2
    - autossh

- name: Install tigervnc
  apt: deb={{ tigervnc_url }}

- name: Copy bash script with kepler env variables
  copy: src=kepler-env.sh dest=/etc/profile.d/kepler-env.sh mode="u=rwx,g=rx,o=rx"

- name: Update java alternatives
  command: update-java-alternatives -s $JAVA
  environment:
    JAVA: "{{ javadir }}"

- name: Install Kepler 2.5
  unarchive: src={{ kepler_url }} dest=/usr/local copy=no keep_newer=yes

- name: git clone kepler indigo repos
  git: repo={{ item.repo }} dest={{ item.dest }} version={{ item.ver }} clone=yes
  with_items:
    - { repo: "https://github.com/indigo-dc/indigoclient.git", dest: "/usr/local/indigoclient", ver: "1.0.0" }
    - { repo: "https://github.com/indigo-dc/indigokepler.git", dest: "/usr/local/indigokepler", ver: "1.0.0" }

- name: mvn install indigoclient
  command: mvn install chdir=/usr/local/indigoclient
  environment:
    JAVA: "{{ javadir }}"
    JAVA_HOME: "{{ java_home }}"
    KEPLER: "{{ kepler_home }}"
    PATH: "{{ ansible_env.PATH }}:{{ kepler_home }}"

- name: mvn initialize indigokepler
  command: mvn initialize chdir=/usr/local/indigokepler
  environment:
    JAVA: "{{ javadir }}"
    JAVA_HOME: "{{ java_home }}"
    KEPLER: "{{ kepler_home }}"
    PATH: "{{ ansible_env.PATH }}:{{ kepler_home }}"

- name: mvn install indigokepler
  command: mvn install chdir=/usr/local/indigokepler
  environment:
    JAVA: "{{ javadir }}"
    JAVA_HOME: "{{ java_home }}"
    KEPLER: "{{ kepler_home }}"
    PATH: "{{ ansible_env.PATH }}:{{ kepler_home }}"

- name: mvn dependency indigokepler
  command: mvn dependency:copy-dependencies -DoutputDirectory=target/indigo/lib/jar -DexcludeArtifactIds=ptolemy chdir=/usr/local/indigokepler
  environment:
    JAVA: "{{ javadir }}"
    JAVA_HOME: "{{ java_home }}"
    KEPLER: "{{ kepler_home }}"
    PATH: "{{ ansible_env.PATH }}:{{ kepler_home }}"

- name: copy target/indigo to $KEPLER
  command: /bin/cp -r /usr/local/indigokepler/target/indigo {{ kepler_home }}/
  environment:
    KEPLER: "{{ kepler_home }}"

- name: insert indigo into kepler modules
  command: /bin/echo "indigo" >> {{ kepler_home }}/build-area/modules.txt
  environment:
    KEPLER: "{{ kepler_home }}"

- name: add user
  user: name={{ user }} password={{ passcript }} shell=/bin/bash groups=adm,sudo system=yes

- name: make user directories
  file: path={{ item }} state=directory mode=0700
  with_items:
    - /home/{{ user }}/.vnc
    - /home/{{ user }}/.config/openbox

- name: copy files
  copy: src={{ item.src }} dest={{ item.dst }} mode=700
  with_items:
    - { src: "vnc_xstartup", dst: "/home/{{ user }}/.vnc/xstartup" }
    - { src: "openbox_autostart", dst: "/home/{{ user }}/.config/openbox/autostart" }
    - { src: "openbox_menu.xml", dst: "/home/{{ user }}/.config/openbox/menu.xml" }

- name: copy templates
  template: src={{ item.src }} dest={{ item.dst }} mode=700
  with_items:
    - { src: "ssh_config.j2", dst: "/home/{{ user }}/.ssh/config" }
    - { src: "init.sh.j2", dst: "/home/{{ user }}/init.sh" }
