---
- name: add repository ppa:openjdk-r/ppa
  apt_repository: repo='ppa:openjdk-r/ppa' update_cache=yes state=present

- name: Install packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - software-properties-common
    - build-essential
    - ant
    - git
    - maven
    - openjdk-8-jdk
    - r-base
    - ssh-import-id
    - tar
    - time
    - ttf-ubuntu-font-family
    - curl
    - x11-utils
    - x11-xkb-utils
    - xauth
    - libfontenc1
    - libgl1-mesa-dri
    - libgnutls28
    - libtasn1-3-bin
    - libxfont1
    - libglu1-mesa
    - openbox
    - tint2
    - autossh

- name: Install tigervnc
  apt: deb={{ tigervnc_url }}

- name: Copy bash script with kepler env variables
  copy: src=kepler-env.sh dest=/etc/profile.d/kepler-env.sh mode="u=rwx,g=rx,o=rx"

- name: Update java alternatives
  command: update-java-alternatives -s $JAVA
  environment:
    JAVA: java-1.8.0-openjdk-amd64

- name: Install Kepler 2.5
  unarchive: src={{ kepler_url }} dest=/usr/local copy=no keep_newer=yes

- name: git clone kepler indigo repos
  git: repo={{ item.repo }} dest={{ item.dest }} version={{ item.ver }} clone=yes
  with_items:
    - { repo: "https://github.com/indigo-dc/indigoclient.git", dest: "/usr/local/indigoclient", ver: "1.0.0" }
    - { repo: "https://github.com/indigo-dc/indigokepler.git", dest: "/usr/local/indigokepler", ver: "1.0.0" }

- name: mvn install indigoclient
  command: mvn install chdir=/usr/local/indigoclient
  environment:
    JAVA: java-1.8.0-openjdk-amd64
    JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64
    KEPLER: /usr/local/Kepler-2.5
    PATH: ${PATH}:/usr/local/Kepler-2.5

- name: mvn initialize indigokepler
  command: mvn initialize chdir=/usr/local/indigokepler
  environment:
    JAVA: java-1.8.0-openjdk-amd64
    JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64
    KEPLER: /usr/local/Kepler-2.5
    PATH: ${PATH}:/usr/local/Kepler-2.5

- name: mvn install indigokepler
  command: mvn install chdir=/usr/local/indigokepler
  environment:
    JAVA: java-1.8.0-openjdk-amd64
    JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64
    KEPLER: /usr/local/Kepler-2.5
    PATH: ${PATH}:/usr/local/Kepler-2.5

- name: mvn dependency indigokepler
  command: mvn dependency:copy-dependencies -DoutputDirectory=target/indigo/lib/jar -DexcludeArtifactIds=ptolemy chdir=/usr/local/indigokepler
  environment:
    JAVA: java-1.8.0-openjdk-amd64
    JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64
    KEPLER: /usr/local/Kepler-2.5
    PATH: ${PATH}:/usr/local/Kepler-2.5
